#!/usr/bin/env bash

# Prototype script for getting mantid and scipp availble in a jupyter notebook
# This is not production ready and has been developed only for OSX

# Cut anything out of the path that might interfere, namely profile set PATHs for Anaconda
export PATH=/usr/bin
# This ensures mantid package is on the path in the notebook
export PYTHONPATH=/Applications/MantidWorkbench.app/Contents/MacOS/
# invoke notebook executable directly avoid selecting wrong versions. Set to open HOME
/Applications/MantidWorkbench.app//Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bin/jupyter-notebook --notebook-dir=~
